### ISSUE TITLE
Import fail Cod2 solo map

### ISSUE THREAD

**Issue by GoldenBlack4** [mauserzjeh/cod-asset-importer#5]
Hello there.
I have the same problem right now with some maps on Cod2:

```
Traceback (most recent call last):
  File "C:\Users\cedri\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\cod_asset_importer\assets\ibsp.py", line 367, in load
    self.entities = self._read_entities(file, self.version, lumps) # entities
  File "C:\Users\cedri\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\cod_asset_importer\assets\ibsp.py", line 322, in _read_entities
    angles.x = float(a[0])
ValueError: could not convert string to float: ''
[ERROR] ibsp.py:394 None
[ERROR] importer.py:40 Error loading map: C:\Users\cedri\Desktop\COD2Master\assets\maps\duhoc_assault.d3dbsp
```
Great improvement btw, thanks!

**Comment by mauserzjeh** [comment]
Hi!

I will try to look at it this weekend. Seems like not all entities have the same angle formats, thus the conversion is failing for some. I will try to get back to you asap.

Thanks for reporting the bug.

**Comment by GoldenBlack4** [comment]
Thank you !

**Comment by mauserzjeh** [comment]
Should be fixed now. [Check the latest release](https://github.com/mauserzjeh/cod-asset-importer/releases/tag/v2.3)
